{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="block">
    <div class="element">
        <label>{'Preferred number of rows'|i18n('design/standard/class/datatype')}:</label>

        <select name="ContentClass_ezrichtext_num_rows_{$class_attribute.id}">
            <option value="2" {if $class_attribute.data_int1|eq(2)} selected="selected" {/if}>2</option>
            <option value="5" {if $class_attribute.data_int1|eq(5)} selected="selected" {/if}>5</option>
            <option value="10" {if $class_attribute.data_int1|eq(10)} selected="selected" {/if}>10</option>
            <option value="15" {if $class_attribute.data_int1|eq(15)} selected="selected" {/if}>15</option>
            <option value="20" {if $class_attribute.data_int1|eq(20)} selected="selected" {/if}>20</option>
            <option value="25" {if $class_attribute.data_int1|eq(25)} selected="selected" {/if}>25</option>
        </select>
    </div>
</div>
